### ISSUE TITLE
Upload model and create a demo on Hugging Face

### ISSUE THREAD

**Issue by adeenayakup** [monniert/differentiable-blocksworld#1]
Hi!

Very cool work! It would be nice to have the model checkpoints on the [Hugging Face Hub](https://huggingface.co/models). 

Some of the benefits of sharing your models through the Hub would be:

* versioning, commit history and diffs
* repos provide useful metadata about their tasks, languages, metrics, etc that make them discoverable
* multiple features from TensorBoard visualizations, PapersWithCode integration, and more
* wider reach of your work to the ecosystem

Creating the repos and adding new models should be a relatively straightforward process if you've used Git before. This is a [step-by-step guide](https://huggingface.co/docs/hub/spaces-sdks-gradio) explaining the process in case you're interested. 

You can also create a[ research demo](https://huggingface.co/docs/hub/spaces-sdks-gradio) as well. 
 
Please let us know if you would be interested and if you have any questions.

**Comment by monniert** [comment]
Hi thanks for reaching out! Since this is an optimization setup, there is no model checkpoints to be used for inference per se + running the model is quite fast (roughly a couple of hours)
