### ISSUE TITLE
About exporting results to mesh

### ISSUE THREAD

**Issue by tyhuang0428** [monniert/differentiable-blocksworld#3]
Hi, thank you for sharing your great work!
I notice that your method can successfully decompose scenes into primitive 3D meshes, which is really cool. Since I only found logging codes for image/video rendering, I would like to know whether inference results can be exported as mesh files. If so, could you also share these mesh files with us?
Thank you very much!

**Comment by monniert** [comment]
Hi tyhuang0428, thanks for the reaching out!

Yes results are exported as a single obj file at the end of the optimisation ([here](https://github.com/monniert/differentiable-blocksworld/blob/7a831638f114f283bf9720061584c52ba397f35c/src/model/dbw.py#L512C9-L512C25) using [this function](https://github.com/monniert/differentiable-blocksworld/blob/7a831638f114f283bf9720061584c52ba397f35c/src/utils/mesh.py#L286)). It is quite straightforward to adapt this function to save one obj file for each primitive to import distinct elements in computer graphics engine for physical simulations (let me know if you don't see how to do it, I could add the function in the code)

Sharing mesh files was not planned as you can get yours in a couple of hours, but I can find a place to add somewhere if you think it is necessary

**Comment by pingpongballz** [comment]
Hi Monniert, 

I tried to modify the functions to export individual primitives, but no luck. Is it possible to upload your implementation over?

Thank you! 😃
