### ISSUE TITLE
what are the meaning of S_world,R_world,and T_world in campanile.yml under configs/nerfstudio?

### ISSUE THREAD

**Issue by Yin-xiongjie** [monniert/differentiable-blocksworld#7]
Congratulations on a job well done. I want to run my custom data on your code. What are the S_world,R_world, and T_world parameters in the yml file under configs/nerfstudio, and what do they do? 
Wish you all the best in your work and look forward to your reply!

**Comment by monniert** [comment]
Hi @Yin-xiongjie thanks for reaching out!

S_world, R_world and T_world are here to adapt the size, orientation and location of your 3D scenes. Basically, default values correspond to a scene located at (0, 0, 0) within [-1, 1]^3 with a y axis pointing upwards (pytorch3d convention) but this may not be your case depending on how your cameras were computed. If you used SFM, I suggest visualizing the resulting sparse point-cloud to check how the 3D scene look like to coarsely adapt these values
